import { Analysis } from '../types/index.ts';

export class ReportGenerator {
  public static generateMarkdownReport(analysis: Analysis): string {
    const dateStr = new Date(analysis.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const goalsList = analysis.goals.map(g => `- **${g.goalText}** (${g.sdgTag || 'SDG 12'})`).join('\n');
    const activitiesList = analysis.activities.map(a => `- **[${a.category}] ${a.name}** (${a.riskLevel} Risk): ${a.description}`).join('\n');

    const contradictionsBlock = analysis.contradictions.map((c, idx) => `
### Contradiction #${idx + 1}: ${c.category} (${c.severity} Severity)
- **Sustainability Goal:** ${c.goal}
- **Planned Action:** ${c.action}
- **Why this is a contradiction:** ${c.explanation}
- **Potential Impact:** ${c.potentialImpact}
- **Recommended Alternative:** ${c.recommendedAlternative}
- **Confidence Rating:** ${(c.confidence * 100).toFixed(0)}%
`).join('\n');

    const categoryBreakdown = analysis.categorySummaries.map(s => `
| ${s.category} | ${s.score}/100 | ${s.riskLevel} | ${s.issueCount} | ${s.recommendationCount} |
`).join('');

    const beforeAfterBlock = analysis.beforeAfterComparisons.map(ba => `
- **Original Action:** ${ba.originalAction} (${ba.originalImpact})
  ➜ **AI-Optimized:** ${ba.improvedAction} (${ba.improvedBenefit})
`).join('\n');

    return `# EcoContradict AI — Sustainability Decision Audit Report
**Project Name:** ${analysis.title}
**Date of Audit:** ${dateStr}
**Primary SDG Alignment:** ${analysis.primarySDG}
**AI Engine Version:** ${analysis.aiProvider} (Confidence: ${(analysis.aiConfidence * 100).toFixed(0)}%)
**Overall Sustainability Score:** ${analysis.score}/100 [${analysis.riskLevel} RISK]

---

## 1. Executive Summary & AI Explanation
${analysis.aiExplanation}

## 2. Defined Sustainability Goals
${goalsList}

## 3. Detected Planned Activities & Logistics
${activitiesList}

## 4. Sustainability Contradictions Detected (${analysis.contradictions.length} Found)
*The system identified the following direct conflicts between stated sustainability goals and planned physical actions:*

${contradictionsBlock}

## 5. Category Risk Assessment
| Category | Score | Risk Level | Issues Flagged | Action Items |
| :--- | :--- | :--- | :--- | :--- |
${categoryBreakdown}

## 6. Transformation Plan: Before vs. After
${beforeAfterBlock}

## 7. Projected Environmental Impact
- **Waste Reduction:** ${analysis.impactEstimate.wasteReduction}
- **Energy Reduction:** ${analysis.impactEstimate.energyReduction}
- **Water Reduction:** ${analysis.impactEstimate.waterReduction}
- **Carbon Reduction:** ${analysis.impactEstimate.carbonReduction || 'Calculated via EPA WARM factors'}
- **Overall Impact Rating:** ${analysis.impactEstimate.estimatedOverallImpact}
- **Methodology Note:** ${analysis.impactEstimate.methodologyNotes}

## 8. Responsible AI & Governance Notice
*This report was produced by EcoContradict AI as a decision-support advisory system.*
- **Human-in-the-Loop:** All recommendations must be validated by event leads and compliance personnel prior to procurement.
- **Configured Assumptions:** Environmental metrics are modeled based on standard life-cycle assessment (LCA) coefficients.
- **Privacy & Safety:** No sensitive personal identities or proprietary credentials were retained in the generation of this assessment.

---
*Generated by EcoContradict AI — "Find sustainability problems before they happen."*
`;
  }
}
